
- name: Ensure we have fail2ban installed
  apt:
    name:
      - fail2ban
    state: present
  notify: restart fail2ban

- name: Configure fail2ban basically
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban